"""End-to-end pipeline to execute RM SOAP queries and export results."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Optional

import pandas as pd
import re

from app.config import ENV
from app.logging import logger
from .parser import DatasetDataFrameBuilder, DatasetNormalizer, SoapResponseParser


@dataclass
class RMQueryETLPipeline:
    """Run the SOAP query pipeline producing a DataFrame and optional CSV export."""

    soap_parser: SoapResponseParser
    normalizer: DatasetNormalizer
    df_builder: DatasetDataFrameBuilder
    exporter: "CSVExporter"
    row_tag: Optional[str] = None

    def run(
        self,
        soap_payload: str | None,
        query_name: str,
    ) -> tuple[pd.DataFrame, Path] | None:
        dataset_xml = self.soap_parser.extract_result_xml(soap_payload)
        if not dataset_xml:
            return None

        dataset_root = self.normalizer.parse(dataset_xml)
        if dataset_root is None:
            return None

        dataframe = self.df_builder.to_dataframe(
            dataset_root,
            row_tag=self.row_tag,
        )
        if dataframe.empty:
            logger.warning("Nenhum registro encontrado para montar o DataFrame.")
            return None

        csv_path = self.exporter.export(dataframe, query_name)
        return dataframe, csv_path


class CSVExporter:
    """Persist the DataFrame generated by the pipeline into a CSV file."""

    SAFE_FILENAME_PATTERN = DatasetDataFrameBuilder.ENCODED_NAME_PATTERN

    def __init__(
        self,
        directory: Path,
        *,
        encoding: str = "utf-8-sig",
        include_index: bool = False,
    ) -> None:
        self.directory = directory
        self.encoding = encoding
        self.include_index = include_index
        self.directory.mkdir(parents=True, exist_ok=True)

    def export(self, dataframe: pd.DataFrame, query_name: str) -> Path:
        safe_name = re.sub(r"[^A-Za-z0-9._-]+", "_", query_name.strip())
        safe_name = safe_name.strip("._") or "consulta"
        csv_path = self.directory / f"{safe_name}.csv"
        dataframe.to_csv(
            csv_path,
            index=self.include_index,
            encoding=self.encoding,
            sep=";",
        )
        logger.info("Resultado salvo em %s", csv_path.resolve())
        return csv_path


def build_pipeline() -> RMQueryETLPipeline:
    """Factory configured via environment variables."""
    soap_parser = SoapResponseParser()
    normalizer = DatasetNormalizer()
    df_builder = DatasetDataFrameBuilder()

    exporter = CSVExporter(
        directory=Path(ENV.get("CSV_OUTPUT_DIR", "consultas_csv")),
        encoding=ENV.get("CSV_OUTPUT_ENCODING", "utf-8-sig"),
        include_index=ENV.get("CSV_INCLUDE_INDEX", "false").lower() == "true",
    )

    row_tag = ENV.get("DATAFRAME_ROW_TAG")
    return RMQueryETLPipeline(
        soap_parser=soap_parser,
        normalizer=normalizer,
        df_builder=df_builder,
        exporter=exporter,
        row_tag=row_tag,
    )
